name: sbt-no-publish
baseurl: /sbt-no-publish
description: Setting No Publication Settings
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+1-cf64afef-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
