name: sbt-no-publish
baseurl: /sbt-no-publish
description: Setting No Publication Settings
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0+5-01978a74-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
